name: Test
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run black
        run: |
          black --check PACKAGE_NAME/ test/
      - name: Run flake8
        run: |
          flake8 PACKAGE_NAME/ test/
  test:
    name: Unit test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [PACKAGE_SUPPORTED_VERSIONS]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Test with pytest
        run: |
          export AWS_DEFAULT_REGION=us-east-1
          pytest --cov=PACKAGE_NAME test/
      - name: "Upload coverage to Codecov"
        if: ${{ github.repository == 'PACKAGE_URL'}}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          flags: unittests